addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master
    - /^(?i:travis).*$/

services: docker

env:
  matrix:
    - INSTANCE=chef12-ubuntu-1604
    - INSTANCE=chef12-ubuntu-1804
    - INSTANCE=chef12-debian-8
    - INSTANCE=chef12-debian-9
    - INSTANCE=chef12-centos-6
    - INSTANCE=chef12-centos-7
    - INSTANCE=chef12-fedora-latest
    - INSTANCE=chef12-amazon
    - INSTANCE=chef13-ubuntu-1604
    - INSTANCE=chef13-ubuntu-1804
    - INSTANCE=chef13-debian-8
    - INSTANCE=chef13-debian-9
    - INSTANCE=chef13-centos-6
    - INSTANCE=chef13-centos-7
    - INSTANCE=chef13-fedora-latest
    - INSTANCE=chef13-amazon

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
